import type { ForgeDungeonPackage } from './dungeonPackage'

export type BuiltinDungeonProp = 'pillar' | 'torch' | 'statue' | 'barrel' | 'crate' | 'rubble' | 'spikes'

export type DungeonDestructible = {
  enabled: true
  template?: string
  health: number
  mass: number
  impulse: number
  bounce: number
  fragmentLifetime: number
  lootEnabled: boolean
  lootChance: number
}

export type DungeonProp = {
  id: string
  name: string
  source: 'builtin' | 'library'
  assetRef: string
  x: number
  y: number
  z: number
  rotationY: number
  scale: number
  roomId?: string
  collision: boolean
  destructible?: DungeonDestructible
}

export type DungeonWithProps = ForgeDungeonPackage & { props?: DungeonProp[] }

export type PropLibraryAsset = {
  id: string
  name: string
  blob: Blob
  destructible?: DungeonDestructible
}

export const BUILTIN_DUNGEON_PROPS: Array<{ id: BuiltinDungeonProp; name: string; hint: string }> = [
  { id: 'pillar', name: 'Stone Pillar', hint: 'architecture' },
  { id: 'torch', name: 'Wall Torch', hint: 'light source' },
  { id: 'statue', name: 'Ancient Statue', hint: 'large decoration' },
  { id: 'barrel', name: 'Barrel', hint: 'clutter' },
  { id: 'crate', name: 'Wooden Crate', hint: 'clutter' },
  { id: 'rubble', name: 'Rubble', hint: 'floor dressing' },
  { id: 'spikes', name: 'Spike Trap', hint: 'hazard prop' },
]

const LEGACY_CRYPT_COLLISION_PREFIX = '__crypt-collision-'

export function dungeonProps(value: DungeonWithProps) {
  // Dungeon Forge V3 owns structural collision through its visible walkable
  // surface. Older saves may still contain invisible __crypt-collision-* props
  // that were generated by the pre-V3 crypt renderer. Never render or collide
  // against those legacy helpers; only user-visible props remain authoritative.
  return (value.props ?? []).filter((prop) => !prop.id.startsWith(LEGACY_CRYPT_COLLISION_PREFIX))
}

export function createDungeonProp(input: {
  name: string
  source: DungeonProp['source']
  assetRef: string
  x: number
  z: number
  y?: number
  roomId?: string
  scale?: number
  rotationY?: number
  collision?: boolean
  destructible?: DungeonDestructible
}): DungeonProp {
  return {
    id: crypto.randomUUID(),
    name: input.name,
    source: input.source,
    assetRef: input.assetRef,
    x: input.x,
    y: input.y ?? 0,
    z: input.z,
    roomId: input.roomId,
    scale: input.scale ?? 1,
    rotationY: input.rotationY ?? 0,
    collision: input.collision ?? input.assetRef !== 'rubble',
    destructible: input.destructible,
  }
}
