export type VfxBlendMode = 'normal' | 'additive'
export type VfxShape = 'point' | 'cone' | 'sphere' | 'box'
export type VfxParticleStyle = 'soft' | 'spark' | 'square' | 'ring' | 'diamond' | 'star'

export type ForgeVfxEmitter = {
  id: string
  name: string
  enabled: boolean
  shape: VfxShape
  style: VfxParticleStyle
  blendMode: VfxBlendMode
  looping: boolean
  duration: number
  spawnRate: number
  burst: number
  maxParticles: number
  lifetime: number
  lifetimeRandom: number
  speed: number
  speedRandom: number
  spreadDeg: number
  direction: [number, number, number]
  gravity: [number, number, number]
  drag: number
  startSize: number
  endSize: number
  startAlpha: number
  endAlpha: number
  startColor: string
  endColor: string
  spin: number
  position: [number, number, number]
  boxSize: [number, number, number]
}

export type ForgeVfxPackage = {
  format: 'forge-vfx-package'
  version: 1
  name: string
  createdAt: string
  looping: boolean
  duration: number
  emitters: ForgeVfxEmitter[]
}

export type VfxPreset = {
  id: string
  name: string
  group: 'combat' | 'magic' | 'environment' | 'stylized'
  description: string
  looping?: boolean
  duration?: number
  emitters: Array<Partial<ForgeVfxEmitter> & Pick<ForgeVfxEmitter, 'name'>>
}

const base = (): ForgeVfxEmitter => ({
  id: crypto.randomUUID(), name: 'Emitter', enabled: true,
  shape: 'point', style: 'soft', blendMode: 'additive', looping: false,
  duration: 1, spawnRate: 0, burst: 28, maxParticles: 220,
  lifetime: 0.7, lifetimeRandom: 0.25, speed: 2.8, speedRandom: 0.6,
  spreadDeg: 80, direction: [0, 1, 0], gravity: [0, -2.5, 0], drag: 0.7,
  startSize: 0.14, endSize: 0.025, startAlpha: 1, endAlpha: 0,
  startColor: '#ffd66b', endColor: '#ff5a24', spin: 0,
  position: [0, 0.08, 0], boxSize: [1, 1, 1],
})

export const VFX_PRESETS: VfxPreset[] = [
  // Combat
  { id:'hit-spark', name:'Hit Sparks', group:'combat', description:'Fast bright contact sparks for melee impacts.', duration:0.8, emitters:[{ name:'Sparks', style:'spark', burst:34, lifetime:.45, speed:4.8, speedRandom:.8, spreadDeg:120, gravity:[0,-4,0], drag:.35, startSize:.075, endSize:.012, startColor:'#fff2a6', endColor:'#ff5a1f' }] },
  { id:'sword-slash', name:'Sword Slash', group:'combat', description:'Directional streak burst for sword swings.', duration:.7, emitters:[{ name:'Slash streaks', style:'spark', burst:42, lifetime:.34, speed:5.6, spreadDeg:28, direction:[1,.25,0], gravity:[0,-.7,0], drag:.25, startSize:.11, endSize:.02, startColor:'#dff6ff', endColor:'#4da8ff' }] },
  { id:'shield-block', name:'Shield Block', group:'combat', description:'Warm contact flash plus short metal sparks.', duration:.85, emitters:[{ name:'Block flash', style:'soft', burst:10, lifetime:.22, speed:1.2, spreadDeg:180, startSize:.28, endSize:.04, startColor:'#fff8cf', endColor:'#ffba45' },{ name:'Metal sparks', style:'spark', burst:24, lifetime:.55, speed:3.8, spreadDeg:120, gravity:[0,-4,0], startSize:.06, endSize:.01, startColor:'#fff0a8', endColor:'#ff642f' }] },
  { id:'arrow-hit', name:'Arrow Hit', group:'combat', description:'Tight impact puff and fragments for projectile hits.', duration:.8, emitters:[{ name:'Impact fragments', style:'square', burst:18, lifetime:.65, speed:2.7, spreadDeg:75, direction:[0,.6,1], gravity:[0,-5,0], startSize:.07, endSize:.035, startColor:'#bfa27b', endColor:'#5b4632', blendMode:'normal' }] },
  { id:'heavy-impact', name:'Heavy Impact', group:'combat', description:'Chunky dust, flash and debris for strong melee hits.', duration:1.1, emitters:[{ name:'Impact flash', style:'star', burst:8, lifetime:.18, speed:1.4, spreadDeg:180, startSize:.3, endSize:.04, startColor:'#fffbe0', endColor:'#ff9f32' },{ name:'Debris', style:'square', blendMode:'normal', burst:24, lifetime:.85, speed:3.2, spreadDeg:130, gravity:[0,-6,0], drag:.2, startSize:.09, endSize:.04, startColor:'#9d856b', endColor:'#493a2d' },{ name:'Dust', shape:'sphere', style:'soft', blendMode:'normal', burst:20, lifetime:1.0, speed:1.25, spreadDeg:180, gravity:[0,.15,0], drag:1.1, startSize:.2, endSize:.5, startAlpha:.45, endAlpha:0, startColor:'#a78d71', endColor:'#6d5b4c' }] },
  { id:'ground-slam', name:'Ground Slam', group:'combat', description:'Wide dirt shock burst for stomps and ground attacks.', duration:1.35, emitters:[{ name:'Ground dust', shape:'box', boxSize:[1.6,.08,1.6], style:'soft', blendMode:'normal', burst:50, lifetime:1.1, speed:1.8, spreadDeg:150, direction:[0,.35,0], gravity:[0,-1.5,0], drag:1.2, startSize:.18, endSize:.44, startAlpha:.55, endAlpha:0, startColor:'#b99b78', endColor:'#6a5848' },{ name:'Rock chips', style:'square', blendMode:'normal', burst:26, lifetime:.95, speed:3.8, spreadDeg:160, gravity:[0,-7,0], startSize:.08, endSize:.04, startColor:'#8d7b67', endColor:'#3e3730' }] },
  { id:'blood-hit', name:'Blood Hit', group:'combat', description:'Short dark-red droplets for non-gory damage feedback.', duration:.95, emitters:[{ name:'Droplets', style:'soft', blendMode:'normal', burst:28, lifetime:.75, speed:3.1, spreadDeg:95, direction:[0,.7,1], gravity:[0,-6.5,0], drag:.18, startSize:.07, endSize:.035, startAlpha:.9, endAlpha:.3, startColor:'#c73535', endColor:'#5f1118' }] },
  { id:'critical-hit', name:'Critical Hit', group:'combat', description:'Big stylized star flash with fast gold streaks.', duration:.9, emitters:[{ name:'Crit star', style:'star', burst:12, lifetime:.35, speed:2.0, spreadDeg:180, startSize:.25, endSize:.05, startColor:'#ffffff', endColor:'#ffd12f' },{ name:'Gold streaks', style:'spark', burst:46, lifetime:.5, speed:5.4, spreadDeg:160, gravity:[0,-2,0], startSize:.08, endSize:.01, startColor:'#fff4a8', endColor:'#ff9f1a' }] },
  { id:'axe-cleave', name:'Axe Cleave', group:'combat', description:'Broad brutal arc-like streak burst with dark fragments.', duration:.8, emitters:[{ name:'Cleave', style:'spark', burst:48, lifetime:.4, speed:6.2, spreadDeg:38, direction:[1,.15,.15], gravity:[0,-1.5,0], startSize:.12, endSize:.018, startColor:'#f3f6f8', endColor:'#8da1ad' },{ name:'Fragments', style:'diamond', blendMode:'normal', burst:16, lifetime:.65, speed:3.2, spreadDeg:90, gravity:[0,-5,0], startSize:.075, endSize:.025, startColor:'#8c7c6e', endColor:'#40362f' }] },
  { id:'hammer-impact', name:'Hammer Impact', group:'combat', description:'Dense stone fragments and a hot center flash.', duration:1.15, emitters:[{ name:'Center flash', style:'soft', burst:12, lifetime:.2, speed:.8, spreadDeg:180, startSize:.34, endSize:.06, startColor:'#fff6d8', endColor:'#ef8b3a' },{ name:'Stone chips', style:'square', blendMode:'normal', burst:36, lifetime:.95, speed:4.1, spreadDeg:155, gravity:[0,-7.5,0], startSize:.09, endSize:.045, startColor:'#a79786', endColor:'#514942' }] },
  { id:'ricochet', name:'Ricochet', group:'combat', description:'Tiny instant spark scatter for metal projectile bounces.', duration:.55, emitters:[{ name:'Ricochet sparks', style:'spark', burst:18, lifetime:.32, speed:6.8, speedRandom:.7, spreadDeg:55, direction:[.6,.7,1], gravity:[0,-4,0], drag:.1, startSize:.05, endSize:.006, startColor:'#ffffff', endColor:'#ff8e2b' }] },
  { id:'parry-flash', name:'Parry Flash', group:'combat', description:'Sharp white-gold star burst for a successful parry.', duration:.6, emitters:[{ name:'Parry star', style:'star', burst:14, lifetime:.26, speed:2.6, spreadDeg:180, startSize:.24, endSize:.035, startColor:'#ffffff', endColor:'#ffd75e' },{ name:'Parry sparks', style:'spark', burst:30, lifetime:.38, speed:5.2, spreadDeg:110, gravity:[0,-2.4,0], startSize:.055, endSize:.008, startColor:'#fff9cb', endColor:'#ff9b22' }] },
  { id:'explosion', name:'Explosion', group:'combat', description:'Layered fireball, smoke and hot debris explosion.', duration:1.8, emitters:[{ name:'Blast core', shape:'sphere', style:'soft', burst:56, lifetime:.8, speed:3.3, spreadDeg:180, gravity:[0,.6,0], drag:1.0, startSize:.3, endSize:.08, startColor:'#fff2a0', endColor:'#ff3c0a' },{ name:'Hot debris', style:'spark', burst:42, lifetime:1.3, speed:5.0, spreadDeg:180, gravity:[0,-5.5,0], drag:.16, startSize:.07, endSize:.012, startColor:'#ffd954', endColor:'#9f1e0b' },{ name:'Smoke', shape:'sphere', style:'soft', blendMode:'normal', burst:34, lifetime:1.6, speed:1.3, spreadDeg:180, gravity:[0,.65,0], drag:1.0, startSize:.34, endSize:.82, startAlpha:.5, endAlpha:0, startColor:'#62564f', endColor:'#25272b' }] },
  { id:'shockwave-hit', name:'Shockwave Hit', group:'combat', description:'Circular energy flecks and flash for force impacts.', duration:.85, emitters:[{ name:'Shock rings', shape:'sphere', style:'ring', burst:28, lifetime:.5, speed:3.6, spreadDeg:180, gravity:[0,0,0], drag:.25, startSize:.16, endSize:.34, startColor:'#e8fbff', endColor:'#65cfff' },{ name:'Core', style:'soft', burst:8, lifetime:.24, speed:.7, spreadDeg:180, startSize:.38, endSize:.04, startColor:'#ffffff', endColor:'#76d9ff' }] },
  { id:'footstep-dust', name:'Footstep Dust', group:'combat', description:'Small low-cost dust puff for footsteps on dry ground.', duration:.65, emitters:[{ name:'Foot dust', shape:'box', boxSize:[.35,.04,.35], style:'soft', blendMode:'normal', burst:12, lifetime:.55, speed:.65, spreadDeg:120, direction:[0,.45,0], gravity:[0,-.5,0], drag:1.1, startSize:.09, endSize:.2, startAlpha:.35, endAlpha:0, startColor:'#a99479', endColor:'#6b5b4c' }] },
  { id:'landing-dust', name:'Landing Dust', group:'combat', description:'Wide dust burst for jumps, falls and heavy landings.', duration:1.0, emitters:[{ name:'Landing dust', shape:'box', boxSize:[1.1,.05,1.1], style:'soft', blendMode:'normal', burst:34, lifetime:.9, speed:1.3, spreadDeg:150, direction:[0,.35,0], gravity:[0,-.8,0], drag:1.2, startSize:.13, endSize:.34, startAlpha:.45, endAlpha:0, startColor:'#b5a084', endColor:'#71604f' }] },

  // Magic
  { id:'fire-burst', name:'Fire Burst', group:'magic', description:'Layered orange flame burst for spells and impacts.', duration:1.4, emitters:[{ name:'Flame core', shape:'sphere', style:'soft', burst:42, lifetime:.9, speed:2.2, spreadDeg:180, gravity:[0,1.4,0], startSize:.24, endSize:.04, startColor:'#fff09a', endColor:'#e52f0c' },{ name:'Embers', style:'spark', burst:28, lifetime:1.2, speed:3.2, spreadDeg:150, gravity:[0,-1.5,0], startSize:.05, endSize:.01, startColor:'#ffd15a', endColor:'#c72a0c' }] },
  { id:'frost-burst', name:'Frost Burst', group:'magic', description:'Cold radial burst with icy shards.', duration:1.2, emitters:[{ name:'Frost mist', shape:'sphere', style:'soft', burst:32, lifetime:1.05, speed:1.3, spreadDeg:180, gravity:[0,.2,0], drag:1.1, startSize:.28, endSize:.5, startAlpha:.65, endAlpha:0, startColor:'#dffcff', endColor:'#6cbcff' },{ name:'Ice shards', style:'spark', burst:20, lifetime:.8, speed:3.4, spreadDeg:180, gravity:[0,-1.2,0], startSize:.065, endSize:.02, startColor:'#ffffff', endColor:'#69c7ff' }] },
  { id:'arcane-orb', name:'Arcane Orb', group:'magic', description:'Continuous violet energy particles around a point.', looping:true, duration:2, emitters:[{ name:'Orb energy', shape:'sphere', style:'soft', looping:true, duration:2, spawnRate:42, burst:0, lifetime:.9, speed:.7, spreadDeg:180, gravity:[0,0,0], drag:1.3, startSize:.13, endSize:.03, startColor:'#f0b6ff', endColor:'#713cff' }] },
  { id:'heal-aura', name:'Healing Aura', group:'magic', description:'Soft rising green motes for healing and buffs.', looping:true, duration:2.5, emitters:[{ name:'Healing motes', shape:'box', boxSize:[1.4,.15,1.4], style:'soft', looping:true, duration:2.5, spawnRate:24, burst:0, lifetime:1.5, speed:.65, spreadDeg:18, direction:[0,1,0], gravity:[0,.2,0], drag:.4, startSize:.12, endSize:.035, startColor:'#c5ffb2', endColor:'#3de38a' }] },
  { id:'poison-cloud', name:'Poison Cloud', group:'magic', description:'Dense drifting toxic mist.', looping:true, duration:3, emitters:[{ name:'Poison mist', shape:'sphere', style:'soft', looping:true, duration:3, spawnRate:34, burst:10, lifetime:2.2, speed:.45, spreadDeg:180, gravity:[0,.08,0], drag:.8, startSize:.3, endSize:.7, startAlpha:.5, endAlpha:0, startColor:'#b8f86c', endColor:'#527b22', blendMode:'normal' }] },
  { id:'lightning-crackle', name:'Lightning Crackle', group:'magic', description:'Fast electric stars and blue-white crackle sparks.', duration:.8, emitters:[{ name:'Electric stars', shape:'sphere', style:'star', burst:26, lifetime:.28, speed:3.0, spreadDeg:180, gravity:[0,0,0], drag:.15, startSize:.16, endSize:.025, startColor:'#ffffff', endColor:'#4bc8ff' },{ name:'Crackle', style:'spark', burst:52, lifetime:.35, speed:6.4, speedRandom:.8, spreadDeg:180, gravity:[0,0,0], drag:.35, startSize:.045, endSize:.006, startColor:'#d8f9ff', endColor:'#477dff' }] },
  { id:'teleport-in', name:'Teleport In', group:'magic', description:'Rising violet motes and rune-like rings for arrivals.', duration:1.5, emitters:[{ name:'Portal rings', shape:'box', boxSize:[1.2,.05,1.2], style:'ring', burst:38, lifetime:1.0, speed:1.2, spreadDeg:18, direction:[0,1,0], gravity:[0,.2,0], drag:.5, startSize:.13, endSize:.3, startColor:'#cda4ff', endColor:'#6546ff' },{ name:'Arrival motes', shape:'box', boxSize:[1,.15,1], style:'soft', burst:44, lifetime:1.25, speed:1.7, spreadDeg:22, direction:[0,1,0], gravity:[0,.15,0], drag:.6, startSize:.09, endSize:.02, startColor:'#f4dcff', endColor:'#8c4cff' }] },
  { id:'teleport-out', name:'Teleport Out', group:'magic', description:'Upward dissolving blue-violet particles for departures.', duration:1.4, emitters:[{ name:'Dissolve', shape:'box', boxSize:[.8,1.8,.8], style:'diamond', burst:64, lifetime:1.1, speed:1.5, spreadDeg:14, direction:[0,1,0], gravity:[0,.4,0], drag:.3, startSize:.08, endSize:.015, startColor:'#b7f0ff', endColor:'#6a43ff', position:[0,.9,0] },{ name:'Exit flash', style:'ring', burst:18, lifetime:.55, speed:2.3, spreadDeg:180, gravity:[0,0,0], startSize:.18, endSize:.4, startColor:'#ffffff', endColor:'#7b5cff' }] },
  { id:'holy-nova', name:'Holy Nova', group:'magic', description:'Radiant gold-white starburst for holy spells.', duration:1.3, emitters:[{ name:'Holy stars', shape:'sphere', style:'star', burst:46, lifetime:.9, speed:2.9, spreadDeg:180, gravity:[0,.2,0], drag:.5, startSize:.16, endSize:.025, startColor:'#ffffff', endColor:'#ffd65c' },{ name:'Holy rings', shape:'sphere', style:'ring', burst:20, lifetime:1.05, speed:2.2, spreadDeg:180, gravity:[0,0,0], startSize:.14, endSize:.36, startColor:'#fffbd6', endColor:'#ffc53a' }] },
  { id:'shadow-burst', name:'Shadow Burst', group:'magic', description:'Dark purple mist and sharp void fragments.', duration:1.4, emitters:[{ name:'Void mist', shape:'sphere', style:'soft', blendMode:'normal', burst:38, lifetime:1.2, speed:1.7, spreadDeg:180, gravity:[0,.25,0], drag:1.1, startSize:.25, endSize:.62, startAlpha:.6, endAlpha:0, startColor:'#5a2c78', endColor:'#130d1e' },{ name:'Void shards', style:'diamond', burst:30, lifetime:.8, speed:4.0, spreadDeg:180, gravity:[0,-.5,0], startSize:.09, endSize:.012, startColor:'#e0a8ff', endColor:'#6d21a8' }] },
  { id:'mana-fountain', name:'Mana Fountain', group:'magic', description:'Continuous upward blue energy fountain.', looping:true, duration:3, emitters:[{ name:'Mana stream', shape:'cone', style:'soft', looping:true, duration:3, spawnRate:58, burst:12, maxParticles:360, lifetime:1.6, speed:2.3, speedRandom:.45, spreadDeg:24, direction:[0,1,0], gravity:[0,-.25,0], drag:.45, startSize:.11, endSize:.035, startColor:'#c9f5ff', endColor:'#347bff' },{ name:'Mana stars', shape:'cone', style:'star', looping:true, duration:3, spawnRate:12, burst:2, lifetime:1.2, speed:1.9, spreadDeg:34, direction:[0,1,0], gravity:[0,.05,0], startSize:.095, endSize:.018, startColor:'#ffffff', endColor:'#62a7ff' }] },
  { id:'wind-gust', name:'Wind Gust', group:'magic', description:'Fast pale streaks and dust motes for wind abilities.', duration:1.1, emitters:[{ name:'Wind streaks', style:'spark', burst:62, lifetime:.75, speed:7.5, spreadDeg:18, direction:[1,.08,0], gravity:[0,0,0], drag:.6, startSize:.07, endSize:.018, startAlpha:.6, endAlpha:0, startColor:'#e9ffff', endColor:'#8adbdc' },{ name:'Wind motes', style:'soft', blendMode:'normal', burst:26, lifetime:1.0, speed:3.6, spreadDeg:26, direction:[1,.12,0], gravity:[0,.05,0], drag:.9, startSize:.08, endSize:.16, startAlpha:.28, endAlpha:0, startColor:'#d9f6e9', endColor:'#9ac7bd' }] },
  { id:'earth-burst', name:'Earth Burst', group:'magic', description:'Brown rock shards with a low dust eruption.', duration:1.45, emitters:[{ name:'Earth shards', style:'diamond', blendMode:'normal', burst:38, lifetime:1.2, speed:3.6, spreadDeg:165, direction:[0,.9,0], gravity:[0,-7,0], startSize:.12, endSize:.06, startColor:'#aa865b', endColor:'#4c3928' },{ name:'Earth dust', shape:'box', boxSize:[1.5,.08,1.5], style:'soft', blendMode:'normal', burst:38, lifetime:1.25, speed:1.4, spreadDeg:150, direction:[0,.45,0], gravity:[0,-.8,0], drag:1.15, startSize:.16, endSize:.48, startAlpha:.48, endAlpha:0, startColor:'#b79570', endColor:'#6b5038' }] },
  { id:'lava-splash', name:'Lava Splash', group:'magic', description:'Molten droplets and ember sparks thrown upward.', duration:1.7, emitters:[{ name:'Molten blobs', style:'soft', burst:30, lifetime:1.35, speed:4.0, spreadDeg:100, direction:[0,1,0], gravity:[0,-7,0], drag:.15, startSize:.14, endSize:.07, startColor:'#fff16e', endColor:'#e02d05' },{ name:'Lava sparks', style:'spark', burst:38, lifetime:1.2, speed:4.8, spreadDeg:130, direction:[0,1,0], gravity:[0,-5,0], startSize:.055, endSize:.008, startColor:'#fff0a2', endColor:'#b51b08' }] },
  { id:'water-splash', name:'Water Splash', group:'magic', description:'Cool blue droplets and mist for water impacts.', duration:1.25, emitters:[{ name:'Water drops', style:'soft', blendMode:'normal', burst:46, lifetime:1.0, speed:4.2, spreadDeg:125, direction:[0,1,0], gravity:[0,-7.5,0], drag:.1, startSize:.075, endSize:.035, startAlpha:.8, endAlpha:.25, startColor:'#c8f5ff', endColor:'#3b8fd8' },{ name:'Splash mist', shape:'box', boxSize:[1.1,.06,1.1], style:'soft', blendMode:'normal', burst:24, lifetime:.85, speed:1.1, spreadDeg:150, direction:[0,.5,0], gravity:[0,-.5,0], drag:1.2, startSize:.12, endSize:.3, startAlpha:.35, endAlpha:0, startColor:'#dffaff', endColor:'#7dbfe4' }] },
  { id:'arcane-portal', name:'Arcane Portal', group:'magic', description:'Looping violet portal dust and rune-like ring sprites.', looping:true, duration:3, emitters:[{ name:'Portal rings', shape:'box', boxSize:[1.9,.05,1.9], style:'ring', looping:true, duration:3, spawnRate:24, burst:16, lifetime:1.3, speed:.35, spreadDeg:10, direction:[0,.25,0], gravity:[0,.05,0], drag:.9, startSize:.16, endSize:.4, startAlpha:.8, endAlpha:0, startColor:'#d4a8ff', endColor:'#7040ff' },{ name:'Portal sparks', shape:'box', boxSize:[1.7,.12,1.7], style:'star', looping:true, duration:3, spawnRate:26, burst:10, lifetime:1.1, speed:.75, spreadDeg:35, direction:[0,1,0], gravity:[0,.1,0], startSize:.08, endSize:.015, startColor:'#ffffff', endColor:'#9e63ff' }] },
  { id:'magic-shield', name:'Magic Shield', group:'magic', description:'Looping cyan shield motes and small energy rings.', looping:true, duration:2.6, emitters:[{ name:'Shield motes', shape:'sphere', style:'soft', looping:true, duration:2.6, spawnRate:42, burst:24, lifetime:1.15, speed:.55, spreadDeg:180, gravity:[0,0,0], drag:1.5, startSize:.09, endSize:.025, startColor:'#e7ffff', endColor:'#46bfff', position:[0,1,0] },{ name:'Shield rings', shape:'sphere', style:'ring', looping:true, duration:2.6, spawnRate:10, burst:8, lifetime:1.0, speed:.45, spreadDeg:180, gravity:[0,0,0], startSize:.11, endSize:.22, startColor:'#dffcff', endColor:'#3ba1ff', position:[0,1,0] }] },
  { id:'curse-aura', name:'Curse Aura', group:'magic', description:'Dark crawling purple particles around the ground.', looping:true, duration:3, emitters:[{ name:'Curse smoke', shape:'box', boxSize:[1.8,.15,1.8], style:'soft', blendMode:'normal', looping:true, duration:3, spawnRate:30, burst:18, lifetime:1.7, speed:.55, spreadDeg:35, direction:[0,1,0], gravity:[0,.05,0], drag:.8, startSize:.15, endSize:.34, startAlpha:.45, endAlpha:0, startColor:'#73438f', endColor:'#1f1228' },{ name:'Curse diamonds', shape:'box', boxSize:[1.6,.12,1.6], style:'diamond', looping:true, duration:3, spawnRate:12, burst:8, lifetime:1.2, speed:.65, spreadDeg:25, direction:[0,1,0], gravity:[0,.12,0], startSize:.06, endSize:.015, startColor:'#cf7fff', endColor:'#7d31a8' }] },
  { id:'electric-aura', name:'Electric Aura', group:'magic', description:'Looping electric sparks around a character-sized volume.', looping:true, duration:2.5, emitters:[{ name:'Electric aura', shape:'box', boxSize:[1.1,2,.8], style:'spark', looping:true, duration:2.5, spawnRate:48, burst:18, lifetime:.38, speed:1.2, spreadDeg:180, gravity:[0,0,0], drag:.8, startSize:.05, endSize:.008, startColor:'#eefcff', endColor:'#3d8cff', position:[0,1,0] },{ name:'Electric stars', shape:'box', boxSize:[1.15,2,.85], style:'star', looping:true, duration:2.5, spawnRate:10, burst:6, lifetime:.45, speed:.8, spreadDeg:180, gravity:[0,0,0], startSize:.1, endSize:.02, startColor:'#ffffff', endColor:'#57c7ff', position:[0,1,0] }] },
  { id:'fire-aura', name:'Fire Aura', group:'magic', description:'Looping embers and flame wisps around the ground.', looping:true, duration:3, emitters:[{ name:'Aura flames', shape:'box', boxSize:[1.5,.16,1.5], style:'soft', looping:true, duration:3, spawnRate:44, burst:12, lifetime:1.1, speed:1.3, spreadDeg:22, direction:[0,1,0], gravity:[0,.4,0], drag:.45, startSize:.14, endSize:.035, startColor:'#fff09a', endColor:'#ef3b0d' },{ name:'Aura embers', shape:'box', boxSize:[1.6,.18,1.6], style:'spark', looping:true, duration:3, spawnRate:18, burst:8, lifetime:1.5, speed:1.5, spreadDeg:30, direction:[0,1,0], gravity:[0,.18,0], startSize:.045, endSize:.008, startColor:'#ffd45c', endColor:'#b9210a' }] },
  { id:'ice-aura', name:'Ice Aura', group:'magic', description:'Frosty ground haze with drifting ice diamonds.', looping:true, duration:3, emitters:[{ name:'Frost haze', shape:'box', boxSize:[1.7,.18,1.7], style:'soft', blendMode:'normal', looping:true, duration:3, spawnRate:28, burst:16, lifetime:1.5, speed:.35, spreadDeg:40, direction:[0,.6,0], gravity:[0,.05,0], drag:1.2, startSize:.18, endSize:.42, startAlpha:.35, endAlpha:0, startColor:'#dffcff', endColor:'#8fcce8' },{ name:'Ice diamonds', shape:'box', boxSize:[1.5,.2,1.5], style:'diamond', looping:true, duration:3, spawnRate:14, burst:8, lifetime:1.45, speed:.85, spreadDeg:20, direction:[0,1,0], gravity:[0,.08,0], startSize:.06, endSize:.018, startColor:'#ffffff', endColor:'#68c8ff' }] },
  { id:'nature-swirl', name:'Nature Swirl', group:'magic', description:'Green motes and leaf-like diamonds for nature spells.', duration:1.6, emitters:[{ name:'Nature motes', shape:'sphere', style:'soft', burst:42, lifetime:1.25, speed:2.0, spreadDeg:180, gravity:[0,.25,0], drag:.8, startSize:.11, endSize:.025, startColor:'#e4ffb7', endColor:'#42c95d' },{ name:'Leaf shards', shape:'sphere', style:'diamond', blendMode:'normal', burst:26, lifetime:1.35, speed:2.4, spreadDeg:180, gravity:[0,-.35,0], drag:.65, startSize:.075, endSize:.03, startColor:'#b8ed76', endColor:'#2f813b' }] },
  { id:'spirit-wisps', name:'Spirit Wisps', group:'magic', description:'Slow floating cyan wisps for ghosts and spirit magic.', looping:true, duration:3.2, emitters:[{ name:'Wisps', shape:'box', boxSize:[2,1.7,2], style:'soft', looping:true, duration:3.2, spawnRate:16, burst:14, maxParticles:160, lifetime:2.4, speed:.28, speedRandom:.8, spreadDeg:180, gravity:[0,.12,0], drag:.5, startSize:.12, endSize:.035, startAlpha:.7, endAlpha:0, startColor:'#d9ffff', endColor:'#51a9b7', position:[0,.8,0] }] },
  { id:'spell-charge', name:'Spell Charge', group:'magic', description:'Dense energy gathering toward a cast point.', looping:true, duration:2.2, emitters:[{ name:'Charge particles', shape:'sphere', style:'diamond', looping:true, duration:2.2, spawnRate:60, burst:10, maxParticles:300, lifetime:.8, speed:.85, spreadDeg:180, gravity:[0,0,0], drag:1.4, startSize:.09, endSize:.025, startColor:'#f8ecff', endColor:'#7d4cff' },{ name:'Charge stars', shape:'sphere', style:'star', looping:true, duration:2.2, spawnRate:12, burst:4, lifetime:.65, speed:.5, spreadDeg:180, gravity:[0,0,0], startSize:.12, endSize:.025, startColor:'#ffffff', endColor:'#b17dff' }] },
  { id:'magic-projectile-trail', name:'Magic Projectile Trail', group:'magic', description:'Continuous compact cyan-purple trail emitter.', looping:true, duration:2, emitters:[{ name:'Trail core', style:'soft', looping:true, duration:2, spawnRate:80, burst:0, maxParticles:320, lifetime:.48, speed:.1, spreadDeg:180, gravity:[0,0,0], drag:2, startSize:.13, endSize:.02, startColor:'#d9ffff', endColor:'#7049ff' },{ name:'Trail stars', style:'star', looping:true, duration:2, spawnRate:16, burst:0, lifetime:.7, speed:.45, spreadDeg:180, gravity:[0,0,0], drag:1, startSize:.075, endSize:.012, startColor:'#ffffff', endColor:'#6bdcff' }] },

  // Environment
  { id:'campfire', name:'Campfire Embers', group:'environment', description:'Looping embers rising from a fire source.', looping:true, duration:3, emitters:[{ name:'Embers', shape:'cone', style:'spark', looping:true, duration:3, spawnRate:18, burst:4, lifetime:1.6, speed:1.2, speedRandom:.7, spreadDeg:26, direction:[0,1,0], gravity:[0,.35,0], drag:.25, startSize:.05, endSize:.012, startColor:'#ffe06b', endColor:'#e53a0c' }] },
  { id:'rain', name:'Rain', group:'environment', description:'Continuous falling rain streaks over a box area.', looping:true, duration:4, emitters:[{ name:'Rain drops', shape:'box', boxSize:[6,.2,6], style:'spark', looping:true, duration:4, spawnRate:150, burst:0, maxParticles:500, lifetime:1.35, lifetimeRandom:.15, speed:8, speedRandom:.12, spreadDeg:3, direction:[0,-1,0], gravity:[0,-4,0], drag:0, startSize:.04, endSize:.03, startAlpha:.65, endAlpha:.25, startColor:'#bfe4ff', endColor:'#5b8fac', blendMode:'normal', position:[0,4,0] }] },
  { id:'snow', name:'Snow', group:'environment', description:'Slow drifting snow over a broad area.', looping:true, duration:5, emitters:[{ name:'Snow flakes', shape:'box', boxSize:[6,.2,6], style:'soft', looping:true, duration:5, spawnRate:60, burst:0, maxParticles:400, lifetime:4.5, lifetimeRandom:.5, speed:.7, speedRandom:.45, spreadDeg:22, direction:[0,-1,0], gravity:[0,-.08,0], drag:.2, startSize:.09, endSize:.07, startAlpha:.9, endAlpha:.35, startColor:'#ffffff', endColor:'#cfe8ff', blendMode:'normal', position:[0,3,0] }] },
  { id:'dust', name:'Dust Motes', group:'environment', description:'Subtle floating particles for rooms and ruins.', looping:true, duration:5, emitters:[{ name:'Dust', shape:'box', boxSize:[4,2.5,4], style:'soft', looping:true, duration:5, spawnRate:18, burst:12, maxParticles:180, lifetime:4.2, speed:.08, speedRandom:.8, spreadDeg:180, gravity:[0,.015,0], drag:.3, startSize:.035, endSize:.02, startAlpha:.35, endAlpha:.05, startColor:'#e6d5b1', endColor:'#b99d73', blendMode:'normal', position:[0,1.2,0] }] },
  { id:'torch-flame', name:'Torch Flame', group:'environment', description:'Compact looping flame and ember effect for torches.', looping:true, duration:2.5, emitters:[{ name:'Torch flame', shape:'cone', style:'soft', looping:true, duration:2.5, spawnRate:48, burst:8, maxParticles:220, lifetime:.75, speed:1.15, speedRandom:.45, spreadDeg:20, direction:[0,1,0], gravity:[0,.45,0], drag:.55, startSize:.15, endSize:.035, startColor:'#fff5a3', endColor:'#f03a0b' },{ name:'Torch embers', shape:'cone', style:'spark', looping:true, duration:2.5, spawnRate:8, burst:2, lifetime:1.25, speed:1.45, spreadDeg:30, direction:[0,1,0], gravity:[0,.2,0], startSize:.04, endSize:.006, startColor:'#ffdf67', endColor:'#a9230c' }] },
  { id:'smoke-plume', name:'Smoke Plume', group:'environment', description:'Slow looping dark smoke column.', looping:true, duration:4, emitters:[{ name:'Smoke', shape:'cone', style:'soft', blendMode:'normal', looping:true, duration:4, spawnRate:24, burst:10, maxParticles:260, lifetime:2.8, lifetimeRandom:.35, speed:.65, speedRandom:.45, spreadDeg:28, direction:[0,1,0], gravity:[0,.18,0], drag:.35, startSize:.22, endSize:.78, startAlpha:.42, endAlpha:0, startColor:'#65676d', endColor:'#282b30' }] },
  { id:'steam-vent', name:'Steam Vent', group:'environment', description:'Bright white steam jet that expands upward.', looping:true, duration:3, emitters:[{ name:'Steam', shape:'cone', style:'soft', blendMode:'normal', looping:true, duration:3, spawnRate:42, burst:12, maxParticles:280, lifetime:1.55, speed:1.9, speedRandom:.35, spreadDeg:24, direction:[0,1,0], gravity:[0,.2,0], drag:.7, startSize:.12, endSize:.5, startAlpha:.42, endAlpha:0, startColor:'#ffffff', endColor:'#bac8cf' }] },
  { id:'fog-patch', name:'Fog Patch', group:'environment', description:'Low drifting ground fog for moody scenes.', looping:true, duration:5, emitters:[{ name:'Ground fog', shape:'box', boxSize:[5,.35,5], style:'soft', blendMode:'normal', looping:true, duration:5, spawnRate:24, burst:24, maxParticles:260, lifetime:4.0, lifetimeRandom:.4, speed:.14, speedRandom:.8, spreadDeg:180, gravity:[0,.01,0], drag:.15, startSize:.5, endSize:1.15, startAlpha:.16, endAlpha:0, startColor:'#d3dde1', endColor:'#9ba8ae', position:[0,.18,0] }] },
  { id:'fireflies', name:'Fireflies', group:'environment', description:'Warm glowing motes drifting through a volume.', looping:true, duration:5, emitters:[{ name:'Fireflies', shape:'box', boxSize:[5,2.8,5], style:'soft', looping:true, duration:5, spawnRate:8, burst:18, maxParticles:120, lifetime:4.2, speed:.18, speedRandom:1.0, spreadDeg:180, gravity:[0,.01,0], drag:.18, startSize:.055, endSize:.03, startAlpha:.95, endAlpha:.25, startColor:'#fff59a', endColor:'#d9e83d', position:[0,1.4,0] }] },
  { id:'falling-leaves', name:'Falling Leaves', group:'environment', description:'Slow falling leaf-like diamonds for forests and autumn.', looping:true, duration:5, emitters:[{ name:'Leaves', shape:'box', boxSize:[6,.25,6], style:'diamond', blendMode:'normal', looping:true, duration:5, spawnRate:22, burst:18, maxParticles:260, lifetime:4.6, lifetimeRandom:.35, speed:.75, speedRandom:.5, spreadDeg:35, direction:[.25,-1,.1], gravity:[0,-.08,0], drag:.15, startSize:.085, endSize:.06, startAlpha:.9, endAlpha:.25, startColor:'#d7a34c', endColor:'#8b4328', position:[0,3.2,0] }] },
  { id:'ash-fall', name:'Ash Fall', group:'environment', description:'Dark floating ash flakes for fires and wastelands.', looping:true, duration:5, emitters:[{ name:'Ash', shape:'box', boxSize:[6,.25,6], style:'square', blendMode:'normal', looping:true, duration:5, spawnRate:34, burst:20, maxParticles:320, lifetime:4.2, speed:.45, speedRandom:.7, spreadDeg:45, direction:[.15,-1,.05], gravity:[0,-.03,0], drag:.2, startSize:.045, endSize:.025, startAlpha:.55, endAlpha:.08, startColor:'#77736e', endColor:'#282828', position:[0,3,0] }] },
  { id:'sand-drift', name:'Sand Drift', group:'environment', description:'Low sideways sand streaks for desert wind.', looping:true, duration:4, emitters:[{ name:'Sand', shape:'box', boxSize:[6,.35,3], style:'spark', blendMode:'normal', looping:true, duration:4, spawnRate:70, burst:25, maxParticles:420, lifetime:1.6, speed:3.1, speedRandom:.45, spreadDeg:12, direction:[1,.03,.1], gravity:[0,-.15,0], drag:.2, startSize:.04, endSize:.02, startAlpha:.45, endAlpha:.05, startColor:'#d7b87a', endColor:'#997344', position:[0,.25,0] }] },
  { id:'waterfall-mist', name:'Waterfall Mist', group:'environment', description:'Cool expanding mist at the base of falling water.', looping:true, duration:3, emitters:[{ name:'Mist', shape:'box', boxSize:[2,.15,1.2], style:'soft', blendMode:'normal', looping:true, duration:3, spawnRate:58, burst:25, maxParticles:360, lifetime:1.25, speed:.95, speedRandom:.6, spreadDeg:125, direction:[0,.55,.3], gravity:[0,-.25,0], drag:1.1, startSize:.11, endSize:.36, startAlpha:.32, endAlpha:0, startColor:'#e8fbff', endColor:'#8ec4d8', position:[0,.15,0] }] },
  { id:'bubble-stream', name:'Bubble Stream', group:'environment', description:'Underwater bubble column with soft ring bubbles.', looping:true, duration:4, emitters:[{ name:'Bubbles', shape:'cone', style:'ring', blendMode:'normal', looping:true, duration:4, spawnRate:22, burst:8, maxParticles:180, lifetime:2.5, speed:.75, speedRandom:.45, spreadDeg:22, direction:[0,1,0], gravity:[0,.2,0], drag:.2, startSize:.07, endSize:.15, startAlpha:.65, endAlpha:.1, startColor:'#dffcff', endColor:'#75bfe8' }] },
  { id:'pollen', name:'Pollen', group:'environment', description:'Tiny golden particles floating in sunlight.', looping:true, duration:5, emitters:[{ name:'Pollen', shape:'box', boxSize:[4,2.6,4], style:'soft', blendMode:'normal', looping:true, duration:5, spawnRate:16, burst:14, maxParticles:150, lifetime:4.0, speed:.08, speedRandom:1, spreadDeg:180, gravity:[0,.008,0], drag:.2, startSize:.028, endSize:.018, startAlpha:.55, endAlpha:.12, startColor:'#ffe8a3', endColor:'#c7a14a', position:[0,1.3,0] }] },
  { id:'snow-gust', name:'Snow Gust', group:'environment', description:'Fast sideways burst of wind-driven snow.', duration:1.7, emitters:[{ name:'Snow gust', shape:'box', boxSize:[3,2,2], style:'soft', blendMode:'normal', burst:90, maxParticles:300, lifetime:1.45, speed:4.3, speedRandom:.35, spreadDeg:16, direction:[1,-.08,.1], gravity:[0,-.2,0], drag:.3, startSize:.07, endSize:.04, startAlpha:.85, endAlpha:.15, startColor:'#ffffff', endColor:'#cfe8ff', position:[-1,1.4,0] }] },
  { id:'storm-rain', name:'Storm Rain', group:'environment', description:'Heavy dense rain for storms and dramatic weather.', looping:true, duration:4, emitters:[{ name:'Heavy rain', shape:'box', boxSize:[7,.2,7], style:'spark', blendMode:'normal', looping:true, duration:4, spawnRate:240, burst:0, maxParticles:800, lifetime:1.2, lifetimeRandom:.12, speed:10, speedRandom:.15, spreadDeg:4, direction:[.08,-1,.03], gravity:[0,-5,0], drag:0, startSize:.045, endSize:.032, startAlpha:.72, endAlpha:.28, startColor:'#d8efff', endColor:'#59798d', position:[0,4.5,0] }] },
  { id:'chimney-smoke', name:'Chimney Smoke', group:'environment', description:'Long-lived pale smoke for houses and workshops.', looping:true, duration:5, emitters:[{ name:'Chimney smoke', shape:'cone', style:'soft', blendMode:'normal', looping:true, duration:5, spawnRate:14, burst:8, maxParticles:180, lifetime:3.8, speed:.55, speedRandom:.35, spreadDeg:18, direction:[.15,1,.05], gravity:[0,.08,0], drag:.18, startSize:.18, endSize:.72, startAlpha:.3, endAlpha:0, startColor:'#aeb3b6', endColor:'#6d7478' }] },
  { id:'lava-embers', name:'Lava Embers', group:'environment', description:'Ambient hot sparks rising over lava.', looping:true, duration:4, emitters:[{ name:'Lava embers', shape:'box', boxSize:[4,.25,4], style:'spark', looping:true, duration:4, spawnRate:26, burst:14, maxParticles:240, lifetime:1.9, speed:1.1, speedRandom:.75, spreadDeg:35, direction:[0,1,0], gravity:[0,.14,0], drag:.18, startSize:.045, endSize:.006, startColor:'#fff06a', endColor:'#c52709', position:[0,.2,0] }] },
  { id:'underwater-plankton', name:'Underwater Plankton', group:'environment', description:'Cool glowing micro-particles for underwater scenes.', looping:true, duration:5, emitters:[{ name:'Plankton', shape:'box', boxSize:[5,3,5], style:'soft', looping:true, duration:5, spawnRate:20, burst:20, maxParticles:200, lifetime:4.2, speed:.07, speedRandom:1, spreadDeg:180, gravity:[0,.015,0], drag:.3, startSize:.025, endSize:.014, startAlpha:.7, endAlpha:.15, startColor:'#9bfff3', endColor:'#2f92a1', position:[0,1.5,0] }] },

  // Stylized
  { id:'loot-pop', name:'Loot Pop', group:'stylized', description:'Bright celebratory pickup burst.', duration:1.1, emitters:[{ name:'Loot sparkle', shape:'sphere', style:'spark', burst:38, lifetime:.85, speed:2.4, spreadDeg:180, gravity:[0,-1.2,0], drag:.4, startSize:.08, endSize:.015, startColor:'#fff8aa', endColor:'#49d7ff' }] },
  { id:'level-up', name:'Level Up', group:'stylized', description:'Upward gold stars and rings for progression feedback.', duration:1.7, emitters:[{ name:'Level stars', shape:'box', boxSize:[1.2,.15,1.2], style:'star', burst:48, lifetime:1.35, speed:2.0, spreadDeg:20, direction:[0,1,0], gravity:[0,.18,0], drag:.45, startSize:.13, endSize:.025, startColor:'#ffffff', endColor:'#ffd02f' },{ name:'Level rings', shape:'box', boxSize:[1.4,.08,1.4], style:'ring', burst:24, lifetime:1.15, speed:1.4, spreadDeg:18, direction:[0,1,0], gravity:[0,.05,0], startSize:.15, endSize:.34, startColor:'#fff6a8', endColor:'#ff9d22' }] },
  { id:'coin-pickup', name:'Coin Pickup', group:'stylized', description:'Compact gold flash for coins and currency pickups.', duration:.8, emitters:[{ name:'Coin star', style:'star', burst:14, lifetime:.45, speed:2.3, spreadDeg:180, gravity:[0,-.6,0], startSize:.14, endSize:.02, startColor:'#ffffff', endColor:'#ffd12f' },{ name:'Coin spark', style:'spark', burst:22, lifetime:.55, speed:3.0, spreadDeg:180, gravity:[0,-1.5,0], startSize:.055, endSize:.008, startColor:'#fff3a2', endColor:'#f2a800' }] },
  { id:'quest-complete', name:'Quest Complete', group:'stylized', description:'Clean green-gold celebratory completion burst.', duration:1.35, emitters:[{ name:'Success stars', shape:'sphere', style:'star', burst:36, lifetime:1.0, speed:2.4, spreadDeg:180, gravity:[0,-.5,0], startSize:.12, endSize:.018, startColor:'#ffffff', endColor:'#77ef74' },{ name:'Success rings', style:'ring', burst:18, lifetime:.8, speed:2.0, spreadDeg:180, gravity:[0,0,0], startSize:.14, endSize:.3, startColor:'#e8ffd8', endColor:'#4dcf70' }] },
  { id:'respawn', name:'Respawn', group:'stylized', description:'Blue-white rebuilding particles rising into place.', duration:1.6, emitters:[{ name:'Respawn motes', shape:'box', boxSize:[1,1.9,1], style:'diamond', burst:74, lifetime:1.35, speed:1.2, spreadDeg:18, direction:[0,1,0], gravity:[0,.15,0], drag:.65, startSize:.07, endSize:.018, startColor:'#eaffff', endColor:'#4c9dff', position:[0,.9,0] },{ name:'Respawn stars', shape:'box', boxSize:[1.1,1.8,1.1], style:'star', burst:22, lifetime:1.0, speed:.8, spreadDeg:35, direction:[0,1,0], gravity:[0,.1,0], startSize:.11, endSize:.02, startColor:'#ffffff', endColor:'#75d6ff', position:[0,.8,0] }] },
  { id:'spawn-poof', name:'Spawn Poof', group:'stylized', description:'Cartoon-like smoke poof for spawning objects or enemies.', duration:1.0, emitters:[{ name:'Poof', shape:'sphere', style:'soft', blendMode:'normal', burst:30, lifetime:.8, speed:1.4, spreadDeg:180, gravity:[0,.15,0], drag:1.2, startSize:.2, endSize:.48, startAlpha:.7, endAlpha:0, startColor:'#f4f4f1', endColor:'#aeb3b7' },{ name:'Pop stars', style:'star', burst:10, lifetime:.5, speed:2.3, spreadDeg:180, gravity:[0,-1,0], startSize:.09, endSize:.012, startColor:'#ffffff', endColor:'#b7c7d1' }] },
  { id:'confetti', name:'Confetti Burst', group:'stylized', description:'Colorful celebration-like square and diamond burst.', duration:2.0, emitters:[{ name:'Gold confetti', style:'square', blendMode:'normal', burst:34, lifetime:1.7, speed:3.7, spreadDeg:130, direction:[0,1,0], gravity:[0,-4.2,0], drag:.12, startSize:.075, endSize:.055, startColor:'#ffe06a', endColor:'#ef8f24' },{ name:'Blue confetti', style:'diamond', blendMode:'normal', burst:30, lifetime:1.8, speed:3.4, spreadDeg:145, direction:[0,1,0], gravity:[0,-4.4,0], startSize:.07, endSize:.05, startColor:'#6ee7ff', endColor:'#4e6cff' },{ name:'Pink confetti', style:'square', blendMode:'normal', burst:30, lifetime:1.75, speed:3.5, spreadDeg:140, direction:[0,1,0], gravity:[0,-4.3,0], startSize:.065, endSize:.045, startColor:'#ff8dd8', endColor:'#b44bff' }] },
  { id:'heart-burst', name:'Heart Burst', group:'stylized', description:'Soft pink romantic burst using stars and glowing motes.', duration:1.25, emitters:[{ name:'Pink stars', shape:'sphere', style:'star', burst:34, lifetime:.95, speed:2.2, spreadDeg:180, gravity:[0,-.8,0], startSize:.13, endSize:.02, startColor:'#fff2fa', endColor:'#ff5ca8' },{ name:'Glow', shape:'sphere', style:'soft', burst:20, lifetime:.85, speed:1.3, spreadDeg:180, gravity:[0,.1,0], startSize:.16, endSize:.04, startColor:'#ffd3eb', endColor:'#d6327b' }] },
  { id:'star-burst', name:'Star Burst', group:'stylized', description:'Pure bright multi-color star pop for arcade feedback.', duration:1.0, emitters:[{ name:'Stars', shape:'sphere', style:'star', burst:54, lifetime:.8, speed:3.2, spreadDeg:180, gravity:[0,-1.4,0], drag:.35, startSize:.12, endSize:.015, startColor:'#ffffff', endColor:'#55d7ff' },{ name:'Warm stars', shape:'sphere', style:'star', burst:28, lifetime:.75, speed:2.8, spreadDeg:180, gravity:[0,-1.1,0], startSize:.1, endSize:.014, startColor:'#fff5b0', endColor:'#ff7a4d' }] },
  { id:'dash-trail', name:'Dash Trail', group:'stylized', description:'Fast cyan streaks for dashes and movement bursts.', duration:.75, emitters:[{ name:'Dash streaks', style:'spark', burst:70, lifetime:.55, speed:7.6, spreadDeg:12, direction:[-1,.05,0], gravity:[0,0,0], drag:.65, startSize:.08, endSize:.01, startAlpha:.8, endAlpha:0, startColor:'#e6ffff', endColor:'#48b8ff' }] },
  { id:'speed-lines', name:'Speed Lines', group:'stylized', description:'Looping directional streak field for high speed.', looping:true, duration:2, emitters:[{ name:'Speed lines', shape:'box', boxSize:[3,2,3], style:'spark', looping:true, duration:2, spawnRate:90, burst:20, maxParticles:420, lifetime:.7, speed:8.5, speedRandom:.25, spreadDeg:5, direction:[0,0,-1], gravity:[0,0,0], drag:.1, startSize:.065, endSize:.018, startAlpha:.55, endAlpha:0, startColor:'#e8faff', endColor:'#6f9bb8', position:[0,1,1.5] }] },
  { id:'cartoon-smoke', name:'Cartoon Smoke', group:'stylized', description:'Chunky light smoke puffs for playful impacts and exits.', duration:1.25, emitters:[{ name:'Smoke puffs', shape:'sphere', style:'soft', blendMode:'normal', burst:38, lifetime:1.05, speed:1.6, spreadDeg:180, gravity:[0,.3,0], drag:1.3, startSize:.18, endSize:.46, startAlpha:.75, endAlpha:0, startColor:'#f4f6f7', endColor:'#9da7ad' }] },
  { id:'rare-loot', name:'Rare Loot Glow', group:'stylized', description:'Looping blue rarity shimmer for valuable drops.', looping:true, duration:2.6, emitters:[{ name:'Rare glow', shape:'cone', style:'soft', looping:true, duration:2.6, spawnRate:24, burst:12, lifetime:1.35, speed:.7, spreadDeg:24, direction:[0,1,0], gravity:[0,.08,0], drag:.55, startSize:.09, endSize:.025, startColor:'#dff8ff', endColor:'#3d8bff' },{ name:'Rare stars', shape:'cone', style:'star', looping:true, duration:2.6, spawnRate:7, burst:4, lifetime:1.1, speed:.85, spreadDeg:35, direction:[0,1,0], startSize:.085, endSize:.012, startColor:'#ffffff', endColor:'#4fc7ff' }] },
  { id:'epic-loot', name:'Epic Loot Glow', group:'stylized', description:'Looping purple-gold high-rarity shimmer.', looping:true, duration:2.6, emitters:[{ name:'Epic glow', shape:'cone', style:'soft', looping:true, duration:2.6, spawnRate:28, burst:14, lifetime:1.4, speed:.75, spreadDeg:28, direction:[0,1,0], gravity:[0,.08,0], drag:.5, startSize:.1, endSize:.025, startColor:'#f5ddff', endColor:'#8a46ff' },{ name:'Epic stars', shape:'cone', style:'star', looping:true, duration:2.6, spawnRate:9, burst:5, lifetime:1.1, speed:.9, spreadDeg:36, direction:[0,1,0], startSize:.09, endSize:.012, startColor:'#fff8bc', endColor:'#c96aff' }] },
  { id:'checkpoint', name:'Checkpoint', group:'stylized', description:'Looping green beacon particles for checkpoints and saves.', looping:true, duration:3, emitters:[{ name:'Checkpoint rings', shape:'box', boxSize:[1.2,.08,1.2], style:'ring', looping:true, duration:3, spawnRate:14, burst:8, lifetime:1.3, speed:.7, spreadDeg:15, direction:[0,1,0], gravity:[0,.05,0], startSize:.14, endSize:.3, startColor:'#eaffd8', endColor:'#47dc67' },{ name:'Checkpoint motes', shape:'box', boxSize:[1,.12,1], style:'soft', looping:true, duration:3, spawnRate:18, burst:8, lifetime:1.45, speed:.85, spreadDeg:18, direction:[0,1,0], gravity:[0,.08,0], startSize:.07, endSize:.02, startColor:'#ffffff', endColor:'#5ddd7b' }] },
  { id:'combo-burst', name:'Combo Burst', group:'stylized', description:'Punchy orange-blue arcade burst for combo milestones.', duration:.95, emitters:[{ name:'Combo stars', shape:'sphere', style:'star', burst:40, lifetime:.72, speed:3.4, spreadDeg:180, gravity:[0,-1.3,0], startSize:.12, endSize:.015, startColor:'#ffffff', endColor:'#ff7d32' },{ name:'Combo diamonds', shape:'sphere', style:'diamond', burst:30, lifetime:.8, speed:3.0, spreadDeg:180, gravity:[0,-1.0,0], startSize:.09, endSize:.014, startColor:'#d8fbff', endColor:'#38a8ff' }] },
]

export function emitterFromPreset(partial?: Partial<ForgeVfxEmitter> & { name?: string }): ForgeVfxEmitter {
  return { ...base(), ...partial, id: crypto.randomUUID(), name: partial?.name ?? 'Emitter', direction: partial?.direction ?? [0,1,0], gravity: partial?.gravity ?? [0,-2.5,0], position: partial?.position ?? [0,.08,0], boxSize: partial?.boxSize ?? [1,1,1] }
}

export function packageFromPreset(preset: VfxPreset): ForgeVfxPackage {
  return { format:'forge-vfx-package', version:1, name:preset.name, createdAt:new Date().toISOString(), looping:!!preset.looping, duration:preset.duration ?? 1, emitters:preset.emitters.map((item) => emitterFromPreset(item)) }
}

export function newVfxPackage(name = 'New VFX'): ForgeVfxPackage {
  return { format:'forge-vfx-package', version:1, name, createdAt:new Date().toISOString(), looping:false, duration:1, emitters:[emitterFromPreset({ name:'Emitter' })] }
}

export function vfxPackageBlob(value: ForgeVfxPackage) {
  return new Blob([JSON.stringify({ ...value, createdAt:new Date().toISOString() }, null, 2)], { type:'application/x-forge-vfx+json' })
}

export async function parseVfxPackage(blob: Blob) {
  try {
    const parsed = JSON.parse(await blob.text()) as ForgeVfxPackage
    if (parsed?.format !== 'forge-vfx-package' || parsed.version !== 1 || !Array.isArray(parsed.emitters)) return undefined
    return parsed
  } catch { return undefined }
}
